language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
script:
    - grunt
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive ./server/**/*.spec.js"
